### ISSUE TITLE
On Rotation issue

### ISSUE THREAD

**Issue by Vaberer** [ytakzk/Hokusai#1]
Hello, I have just used your library. It looks very convenient and great. But I found out, there is an issue, if I rotate a phone, menu will not adjust properly.

**Comment by ytakzk** [comment]
I already worked on this and pushed the revised version just now.
It still needs refactoring but it works correctly.
Thank you!

**Comment by Vaberer** [comment]
Good job! I was looking at your code and how it is written. I wanted to fix it by myself but I have more experience with creating UI with constraints instead of autoresizing masks and frames.

Did you try to create UI only with constraints programmatically?

**Comment by ytakzk** [comment]
I wanted to use constraints but found that it takes more time for me to implement with constraint than with frames without a storyboard.
I will try to rewrite with constraints in the near feature but your pull request of the implementation is always welcome!

**Comment by Vaberer** [comment]
When I started using constraints, it was a little bit challenging, but now it is quite easy:)

Once again, good job:)
