### ISSUE TITLE
Title Text and Description

### ISSUE THREAD

**Issue by pixelbendr** [ytakzk/Hokusai#10]
Hello how can I add a title text and description for better user experience and also to match the original action sheet from Apple. :)

**Comment by ytakzk** [comment]
@pixelbendr Thank you for your suggestion. Let me implement the feature when I have time.

**Comment by pixelbendr** [comment]
ok. perfect. :)

**Comment by limfinity** [comment]
I started working on an implementation in my fork, for now it uses a more generic approach to add as many labels as you want. I mean to open a PR in the near future, but if you can't wait for it go ahead and get it directly from the fork.
https://github.com/limfinity/Hokusai/tree/labels

**Comment by ytakzk** [comment]
@limfinity Thank you! I can wait for your PR. Looking forward to it!

**Comment by ytakzk** [comment]
@limfinity Super cool pull request! Thanks a lot!

**Comment by limfinity** [comment]
You're most welcome!
