### ISSUE TITLE
Fix for rotation issue

### ISSUE THREAD

**Issue by rogomantik** [ytakzk/Hokusai#5]
There is an issue to the rotation Portrait -> Landscape
To recreate the problem:
Launch the app in portrait. do not rotate
Open the menu when the device is still vertically
Rotate the device
- the shapeLayer.fillColor is drew with portrait dimensions ("background" half coloured, half transparent)

My fix
menuView. shapeLayer. frame = frame menuView.
menuView. shapeLayer. bounds. origin = origin menuView. frame.
**menuView. updatePath ()   //ADD THIS LINE**
menuView. shapeLayer. layoutIfNeeded ()
menuView. layoutIfNeeded ()

I don't know if it's the right time to call menuView.updatePath()
Perhaps it would be better to call it somewhere else or change something else

**Comment by AlexCatch** [comment]
+1

**Comment by ytakzk** [comment]
@rogomantik @AlexCatch I fixed this bug. Thanks!

**Comment by AlexCatch** [comment]
@ytakzk Issue does not appear to be fixed on iPad.

**Comment by ytakzk** [comment]
@AlexCatch I have never debugged on iPad. Let me fix it.

**Comment by ytakzk** [comment]
@AlexCatch I fixed the bug on iPad too. Could you verify it?

**Comment by AlexCatch** [comment]
@ytakzk I can confirm it is fixed. Thanks!

**Comment by ytakzk** [comment]
@AlexCatch Good.
