### ISSUE TITLE
cancel button's color same as default button

### ISSUE THREAD

**Issue by SptrsCA** [ytakzk/Hokusai#6]
the cancel button's color always equal default button
even I use the custom UIColor Or change the preset colors parameter.

**Comment by ytakzk** [comment]
@iCnSF I am sorry but cannot reproduce it . Did you use the same code as written in README.md? Please let me know if you still have the same problem.

```
hokusai.colors = HOKColors(
    backGroundColor: UIColor.blackColor(),
    buttonColor: UIColor.purpleColor(),
    cancelButtonColor: UIColor.grayColor(),
    fontColor: UIColor.whiteColor()
)
```

**Comment by iCnSF** [comment]
yeah..My code 👇
    //   Mark:长按响应
    func longPress(recognizer: UILongPressGestureRecognizer){
        if(recognizer.state == UIGestureRecognizerState.Began)
        {
            let point : CGPoint = recognizer.locationInView(self.collectionView)
            let indexPath : NSIndexPath = (self.collectionView?.indexPathForItemAtPoint(point))!
            print(indexPath.row)
            
            let hokusai = Hokusai()
            
            // Add a button with a closure
            hokusai.addButton("取消订阅"){
                
            }
            hokusai.addButton("举报"){
                
            }
            hokusai.cancelButtonTitle = "完成"
            hokusai.cancelButtonAction = {
                print("canceled")
            }
            
            hokusai.fontName = "Verdana-Bold"
            hokusai.colorScheme = HOKColorScheme.Hokusai
            hokusai.show()
        }
    }

**Comment by ytakzk** [comment]
@iCnSF Could you paste the screenshot here?

**Comment by iCnSF** [comment]
ok.
![Uploading 8C3D223B-C2D5-429B-A429-C572FD27037F.jpeg…]()

**Comment by iCnSF** [comment]
ops...
It's something wrong about uploading...
what's your email ?

**Comment by ytakzk** [comment]
@iCnSF I found the problem here and fixed it. Could you verify that it has fixed?

**Comment by SptrsCA** [comment]
It's work. THX~

**Comment by ytakzk** [comment]
@iCnSF You are welcome! Have a nice Hokusai life:surfer:
